import { PrismaClient, HiringDemand, ResourceProvider, ResourceType, ResourceStatus, SkillDifficulty, CourseLevel } from '@prisma/client';

export async function seedLearningResources(prisma: PrismaClient) {
  console.log('Seeding learning resources and skill intelligence data...');

  const skillData = [
    {
      name: 'Docker',
      hiringDemand: HiringDemand.CORE,
      estimatedWeeks: 2,
      projectSuggestion: 'Containerize a Todo REST API with Docker Compose',
      projectDifficulty: SkillDifficulty.BEGINNER,
      projectHours: 4,
      projectOutcome: 'Add "Docker containerized Node.js REST API with PostgreSQL database via Docker Compose" to CV Projects section',
      resources: [
        {
          title: 'Docker Getting Started Guide',
          description: 'Official Docker setup guide and basic concepts documentation.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Docker Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://docs.docker.com/get-started/',
          level: CourseLevel.BEGINNER,
          durationMin: 45,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'Play with Docker Classroom',
          description: 'Official interactive online lab environment by Docker.',
          provider: ResourceProvider.INTERACTIVE,
          providerLabel: 'Docker Labs',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 2,
          url: 'https://labs.play-with-docker.com/',
          level: CourseLevel.BEGINNER,
          durationMin: 120,
          isPaid: false,
          qualityScore: 98,
        },
        {
          title: 'Docker and Containers Full Course',
          description: 'A comprehensive video course covering Docker images, containers, networks, and volumes.',
          provider: ResourceProvider.FREECODECAMP,
          providerLabel: 'freeCodeCamp',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=fqm5bOMd-Kg',
          level: CourseLevel.BEGINNER,
          durationMin: 220,
          isPaid: false,
          qualityScore: 94,
        },
        {
          title: 'Docker in 100 Seconds',
          description: 'A rapid overview of Docker containers and images.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Fireship',
          resourceType: ResourceType.VIDEO,
          learningOrder: 4,
          url: 'https://www.youtube.com/watch?v=Gjnup-PuquQ',
          level: CourseLevel.BEGINNER,
          durationMin: 2,
          isPaid: false,
          qualityScore: 92,
        },
        {
          title: 'Docker Compose Guide',
          description: 'How to define and run multi-container Docker applications.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Docker Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 5,
          url: 'https://docs.docker.com/compose/',
          level: CourseLevel.INTERMEDIATE,
          durationMin: 30,
          isPaid: false,
          qualityScore: 96,
        }
      ]
    },
    {
      name: 'Redis',
      hiringDemand: HiringDemand.IMPORTANT,
      estimatedWeeks: 1,
      projectSuggestion: 'Implement a Redis caching layer for API endpoints',
      projectDifficulty: SkillDifficulty.INTERMEDIATE,
      projectHours: 3,
      projectOutcome: 'Demonstrate performance optimization on CV: "Integrated Redis cache, reducing database read latency by 85%"',
      resources: [
        {
          title: 'Redis Documentation',
          description: 'Official Redis commands, data structures, and setup documentation.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Redis Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://redis.io/docs/',
          level: CourseLevel.BEGINNER,
          durationMin: 60,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'Redis University',
          description: 'Official interactive Redis courses and labs.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Redis University',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 2,
          url: 'https://university.redis.com/',
          level: CourseLevel.BEGINNER,
          durationMin: 300,
          isPaid: false,
          qualityScore: 97,
        },
        {
          title: 'Redis Crash Course for Beginners',
          description: 'A beginner friendly overview of Redis data types, CLI, and Node.js integration.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Traversy Media',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=jgpVdJB2sKQ',
          level: CourseLevel.BEGINNER,
          durationMin: 40,
          isPaid: false,
          qualityScore: 92,
        },
        {
          title: 'Redis in 100 Seconds',
          description: 'A quick summary of key-value stores and Redis use cases.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Fireship',
          resourceType: ResourceType.VIDEO,
          learningOrder: 4,
          url: 'https://www.youtube.com/watch?v=Hbt56gFj998',
          level: CourseLevel.BEGINNER,
          durationMin: 2,
          isPaid: false,
          qualityScore: 90,
        },
        {
          title: 'Caching Patterns in Redis',
          description: 'Detailed tutorial on Cache-Aside, Write-Through, and Cache invalidation.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Redis Developer',
          resourceType: ResourceType.DOCS,
          learningOrder: 5,
          url: 'https://redis.io/docs/manual/client-side-caching/',
          level: CourseLevel.ADVANCED,
          durationMin: 45,
          isPaid: false,
          qualityScore: 95,
        }
      ]
    },
    {
      name: 'TypeScript',
      hiringDemand: HiringDemand.CORE,
      estimatedWeeks: 2,
      projectSuggestion: 'Refactor a JavaScript project to strict TypeScript',
      projectDifficulty: SkillDifficulty.INTERMEDIATE,
      projectHours: 5,
      projectOutcome: 'Show type safety proficiency: "Refactored codebase to strict TypeScript, eliminating runtime type errors"',
      resources: [
        {
          title: 'TypeScript Handbook',
          description: 'The definitive guide to learning TypeScript language features.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'TS Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
          level: CourseLevel.BEGINNER,
          durationMin: 180,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'TypeScript Playground',
          description: 'Official interactive playground to test TypeScript code directly in browser.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'TS Playground',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 2,
          url: 'https://www.typescriptlang.org/play',
          level: CourseLevel.BEGINNER,
          durationMin: 60,
          isPaid: false,
          qualityScore: 98,
        },
        {
          title: 'TypeScript Exercises',
          description: 'A set of interactive TypeScript exercises to test your type logic skills.',
          provider: ResourceProvider.EXERCISM,
          providerLabel: 'Exercism TS Track',
          resourceType: ResourceType.PRACTICE,
          learningOrder: 3,
          url: 'https://exercism.org/tracks/typescript',
          level: CourseLevel.INTERMEDIATE,
          durationMin: 240,
          isPaid: false,
          qualityScore: 95,
        },
        {
          title: 'TypeScript Tutorial for Beginners',
          description: 'Excellent video resource introducing core types, interfaces, classes, and generics.',
          provider: ResourceProvider.FREECODECAMP,
          providerLabel: 'freeCodeCamp',
          resourceType: ResourceType.VIDEO,
          learningOrder: 4,
          url: 'https://www.youtube.com/watch?v=30LWjhZzg50',
          level: CourseLevel.BEGINNER,
          durationMin: 320,
          isPaid: false,
          qualityScore: 93,
        },
        {
          title: 'Total TypeScript Essentials',
          description: 'Curated tutorials on advanced TypeScript, utility types, and generics.',
          provider: ResourceProvider.OTHER,
          providerLabel: 'Total TypeScript',
          resourceType: ResourceType.ARTICLE,
          learningOrder: 5,
          url: 'https://www.totaltypescript.com/tutorials',
          level: CourseLevel.ADVANCED,
          durationMin: 150,
          isPaid: false,
          qualityScore: 96,
        }
      ]
    },
    {
      name: 'NestJS',
      hiringDemand: HiringDemand.CORE,
      estimatedWeeks: 2,
      projectSuggestion: 'Build a modular REST API with authentication and database integration',
      projectDifficulty: SkillDifficulty.INTERMEDIATE,
      projectHours: 8,
      projectOutcome: 'Show modular backend structure: "Architected a scalable NestJS REST API with PostgreSQL, using JWT auth and repository pattern"',
      resources: [
        {
          title: 'NestJS Official Documentation',
          description: 'Thorough guides covering NestJS architecture: Modules, Controllers, Providers, and Guards.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'NestJS Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://docs.nestjs.com/',
          level: CourseLevel.BEGINNER,
          durationMin: 120,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'NestJS Full Course for Beginners',
          description: 'Step-by-step video guide to building a complete REST API using controllers, services, modules, and Prisma.',
          provider: ResourceProvider.FREECODECAMP,
          providerLabel: 'freeCodeCamp',
          resourceType: ResourceType.VIDEO,
          learningOrder: 2,
          url: 'https://www.youtube.com/watch?v=2n3xS89TJMI',
          level: CourseLevel.BEGINNER,
          durationMin: 310,
          isPaid: false,
          qualityScore: 95,
        },
        {
          title: 'NestJS Crash Course',
          description: 'A fast-paced video introduction to building an API with dependency injection and TypeORM.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Marius Espejo',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=wqhveSoxUko',
          level: CourseLevel.BEGINNER,
          durationMin: 45,
          isPaid: false,
          qualityScore: 91,
        },
        {
          title: 'Official NestJS Courses',
          description: 'Structured NestJS courses from the framework creators (NestJS Fundamentals).',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'NestJS Academy',
          resourceType: ResourceType.COURSE,
          learningOrder: 4,
          url: 'https://courses.nestjs.com/',
          level: CourseLevel.BEGINNER,
          durationMin: 600,
          isPaid: true,
          qualityScore: 96,
        }
      ]
    },
    {
      name: 'React',
      hiringDemand: HiringDemand.CORE,
      estimatedWeeks: 2,
      projectSuggestion: 'Create a state-managed dashboard application with hooks',
      projectDifficulty: SkillDifficulty.BEGINNER,
      projectHours: 6,
      projectOutcome: 'Show frontend proficiency: "Developed a responsive React web app utilizing custom hooks, Context API, and integration with REST endpoints"',
      resources: [
        {
          title: 'React Documentation',
          description: 'The official guides for modern React using functional components and hooks.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'React Dev',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://react.dev/',
          level: CourseLevel.BEGINNER,
          durationMin: 120,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'React.dev Tutorials & Tic-Tac-Toe',
          description: 'Interactive tutorial to build your first React application directly step-by-step.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'React Dev',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 2,
          url: 'https://react.dev/learn',
          level: CourseLevel.BEGINNER,
          durationMin: 90,
          isPaid: false,
          qualityScore: 98,
        },
        {
          title: 'React Course for Beginners',
          description: 'A complete React developer path covering JSX, components, state, props, and API calls.',
          provider: ResourceProvider.FREECODECAMP,
          providerLabel: 'freeCodeCamp',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
          level: CourseLevel.BEGINNER,
          durationMin: 700,
          isPaid: false,
          qualityScore: 94,
        },
        {
          title: 'React in 100 Seconds',
          description: 'An elegant high-level overview of React components and virtual DOM.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Fireship',
          resourceType: ResourceType.VIDEO,
          learningOrder: 4,
          url: 'https://www.youtube.com/watch?v=Tn6-PIqc4UM',
          level: CourseLevel.BEGINNER,
          durationMin: 2,
          isPaid: false,
          qualityScore: 90,
        },
        {
          title: 'Learn React for Free on Scrimba',
          description: 'Highly interactive code-along React course.',
          provider: ResourceProvider.OTHER,
          providerLabel: 'Scrimba',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 5,
          url: 'https://scrimba.com/learn/learnreact',
          level: CourseLevel.BEGINNER,
          durationMin: 480,
          isPaid: false,
          qualityScore: 95,
        }
      ]
    },
    {
      name: 'Kubernetes',
      hiringDemand: HiringDemand.IMPORTANT,
      estimatedWeeks: 3,
      projectSuggestion: 'Deploy a multi-service containerized application to a local Minikube cluster',
      projectDifficulty: SkillDifficulty.INTERMEDIATE,
      projectHours: 6,
      projectOutcome: 'Demonstrate orchestration skills on CV: "Orchestrated container deployments in Kubernetes with services, config maps, and persistent volumes"',
      resources: [
        {
          title: 'Kubernetes Documentation',
          description: 'Official docs covering architecture, pods, deployments, services, and ingress.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'K8s Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://kubernetes.io/docs/home/',
          level: CourseLevel.BEGINNER,
          durationMin: 180,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'Killercoda Kubernetes Playground',
          description: 'Free interactive browser-based terminal labs for Kubernetes.',
          provider: ResourceProvider.INTERACTIVE,
          providerLabel: 'Killercoda',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 2,
          url: 'https://killercoda.com/playgrounds',
          level: CourseLevel.BEGINNER,
          durationMin: 120,
          isPaid: false,
          qualityScore: 98,
        },
        {
          title: 'Kubernetes Tutorial for Beginners',
          description: 'Superb visual explanation of pods, deployments, services, namespaces, and configMaps.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'TechWorld with Nana',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=X48VuDVv0do',
          level: CourseLevel.BEGINNER,
          durationMin: 220,
          isPaid: false,
          qualityScore: 96,
        },
        {
          title: 'Kubernetes in 100 Seconds',
          description: 'Rapid summary of container orchestration concepts.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Fireship',
          resourceType: ResourceType.VIDEO,
          learningOrder: 4,
          url: 'https://www.youtube.com/watch?v=PziYgegFjHY',
          level: CourseLevel.BEGINNER,
          durationMin: 2,
          isPaid: false,
          qualityScore: 90,
        },
        {
          title: 'Kubernetes Bootcamp on KodeKloud',
          description: 'Interactive courses and labs targeting CKA topics.',
          provider: ResourceProvider.INTERACTIVE,
          providerLabel: 'KodeKloud K8s',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 5,
          url: 'https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on/',
          level: CourseLevel.BEGINNER,
          durationMin: 360,
          isPaid: true,
          qualityScore: 94,
        }
      ]
    },
    {
      name: 'PostgreSQL',
      hiringDemand: HiringDemand.CORE,
      estimatedWeeks: 2,
      projectSuggestion: 'Design a normalized database schema with complex JOINs and indexes',
      projectDifficulty: SkillDifficulty.BEGINNER,
      projectHours: 5,
      projectOutcome: 'Show relational DB design: "Designed PostgreSQL schema with optimized composite indexes and foreign keys, improving query execution times by 40%"',
      resources: [
        {
          title: 'PostgreSQL Official Documentation',
          description: 'Complete SQL reference, data types, indexing strategies, and performance tunings.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Postgres Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://www.postgresql.org/docs/',
          level: CourseLevel.BEGINNER,
          durationMin: 120,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'Interactive PostgreSQL Exercises',
          description: 'A platform to practice SQL queries, JOINs, and aggregates with instant feedback.',
          provider: ResourceProvider.LEETCODE,
          providerLabel: 'pgexercises.com',
          resourceType: ResourceType.PRACTICE,
          learningOrder: 2,
          url: 'https://pgexercises.com/',
          level: CourseLevel.BEGINNER,
          durationMin: 180,
          isPaid: false,
          qualityScore: 98,
        },
        {
          title: 'PostgreSQL Course for Beginners',
          description: 'Complete video course covering table creation, query structure, relations, and operations.',
          provider: ResourceProvider.FREECODECAMP,
          providerLabel: 'freeCodeCamp',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=qw--VYLgGeg',
          level: CourseLevel.BEGINNER,
          durationMin: 260,
          isPaid: false,
          qualityScore: 93,
        },
        {
          title: 'CMU 15-445 Database Systems Lectures',
          description: 'Highly advanced academic lectures on database internals, storage engines, and indexes.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Carnegie Mellon University',
          resourceType: ResourceType.VIDEO,
          learningOrder: 4,
          url: 'https://www.youtube.com/watch?v=Fm7S33V1t0Y&list=PLSE8ODhjFmyybha5QDac7dy5dFCF595Y-',
          level: CourseLevel.ADVANCED,
          durationMin: 1200,
          isPaid: false,
          qualityScore: 96,
        },
        {
          title: 'Use The Index, Luke!',
          description: 'A programmer\'s guide to SQL indexing and database performance.',
          provider: ResourceProvider.OTHER,
          providerLabel: 'Use The Index Docs',
          resourceType: ResourceType.ARTICLE,
          learningOrder: 5,
          url: 'https://use-the-index-luke.com/',
          level: CourseLevel.INTERMEDIATE,
          durationMin: 90,
          isPaid: false,
          qualityScore: 95,
        }
      ]
    },
    {
      name: 'AWS',
      hiringDemand: HiringDemand.IMPORTANT,
      estimatedWeeks: 3,
      projectSuggestion: 'Deploy a secure web app architecture with EC2, VPC, RDS, and S3',
      projectDifficulty: SkillDifficulty.INTERMEDIATE,
      projectHours: 6,
      projectOutcome: 'Show cloud infrastructure skills: "Provisioned AWS infrastructure using EC2, RDS, and S3, with security groups and automated backups"',
      resources: [
        {
          title: 'AWS Documentation Portal',
          description: 'Official AWS resource, listing getting started guides for Core Services (EC2, S3, IAM, RDS).',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'AWS Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://docs.aws.amazon.com/',
          level: CourseLevel.BEGINNER,
          durationMin: 120,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'AWS Certified Cloud Practitioner Training',
          description: 'Free comprehensive course covering AWS cloud concepts, security, technology, and billing.',
          provider: ResourceProvider.FREECODECAMP,
          providerLabel: 'freeCodeCamp CCP Video',
          resourceType: ResourceType.VIDEO,
          learningOrder: 2,
          url: 'https://www.youtube.com/watch?v=SOTamWGuDKc',
          level: CourseLevel.BEGINNER,
          durationMin: 780,
          isPaid: false,
          qualityScore: 94,
        },
        {
          title: 'AWS Skill Builder',
          description: 'Interactive learning paths and official cloud labs provided by AWS.',
          provider: ResourceProvider.AWS_SKILL_BUILDER,
          providerLabel: 'AWS Skill Builder',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 3,
          url: 'https://skillbuilder.aws/',
          level: CourseLevel.BEGINNER,
          durationMin: 240,
          isPaid: false,
          qualityScore: 97,
        },
        {
          title: 'Adrian Cantrill AWS Courses',
          description: 'Exceptionally structured deep-dive training for AWS certifications and real-world skills.',
          provider: ResourceProvider.OTHER,
          providerLabel: 'Cantrill.io',
          resourceType: ResourceType.COURSE,
          learningOrder: 4,
          url: 'https://learn.cantrill.io/',
          level: CourseLevel.INTERMEDIATE,
          durationMin: 1800,
          isPaid: true,
          qualityScore: 99,
        }
      ]
    },
    {
      name: 'Kafka',
      hiringDemand: HiringDemand.IMPORTANT,
      estimatedWeeks: 3,
      projectSuggestion: 'Implement a pub/sub event-driven flow between two microservices',
      projectDifficulty: SkillDifficulty.ADVANCED,
      projectHours: 8,
      projectOutcome: 'Show distributed architecture skills: "Designed event-driven messaging layer using Apache Kafka, decoupling services and scaling event throughput"',
      resources: [
        {
          title: 'Apache Kafka Documentation',
          description: 'Official Kafka architecture, APIs, consumer groups, offsets, and configs guide.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Kafka Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://kafka.apache.org/documentation/',
          level: CourseLevel.BEGINNER,
          durationMin: 120,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'Confluent Developer Portal',
          description: 'Official tutorials, interactive labs, and guides on Kafka and event streaming.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Confluent Developer',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 2,
          url: 'https://developer.confluent.io/',
          level: CourseLevel.BEGINNER,
          durationMin: 240,
          isPaid: false,
          qualityScore: 98,
        },
        {
          title: 'Apache Kafka Crash Course',
          description: 'Overview of distributed streaming, brokers, partitions, replication, and consumer groups.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Hussein Nasser',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=R87356m77Y4',
          level: CourseLevel.INTERMEDIATE,
          durationMin: 90,
          isPaid: false,
          qualityScore: 94,
        },
        {
          title: 'Kafka in 100 Seconds',
          description: 'An introductory video on messaging brokers and pub-sub systems.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'Fireship',
          resourceType: ResourceType.VIDEO,
          learningOrder: 4,
          url: 'https://www.youtube.com/watch?v=i9vV1K_2tGg',
          level: CourseLevel.BEGINNER,
          durationMin: 2,
          isPaid: false,
          qualityScore: 90,
        },
        {
          title: 'Apache Kafka Complete Developer Course',
          description: 'Outstanding Udemy course covering programming producer/consumer clients and deployment.',
          provider: ResourceProvider.UDEMY,
          providerLabel: 'Stephane Maarek',
          resourceType: ResourceType.COURSE,
          learningOrder: 5,
          url: 'https://www.udemy.com/course/apache-kafka-for-beginners/',
          level: CourseLevel.INTERMEDIATE,
          durationMin: 540,
          isPaid: true,
          qualityScore: 95,
        }
      ]
    },
    {
      name: 'System Design',
      hiringDemand: HiringDemand.CORE,
      estimatedWeeks: 2,
      projectSuggestion: 'Write a comprehensive architecture proposal for a scale database/API system',
      projectDifficulty: SkillDifficulty.ADVANCED,
      projectHours: 10,
      projectOutcome: 'Show system architect thinking: "Authored system architecture design document addressing load balancing, horizontal scaling, caching, and failover mechanisms"',
      resources: [
        {
          title: 'System Design Primer',
          description: 'GitHub repository for system design prep with diagrams, study templates, and cheat sheets.',
          provider: ResourceProvider.GITHUB,
          providerLabel: 'System Design Primer',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://github.com/donnemartin/system-design-primer',
          level: CourseLevel.BEGINNER,
          durationMin: 360,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'ByteByteGo System Design Basics',
          description: 'Excellent video series by Alex Xu explaining load balancers, CDN, proxies, scaling, and database replication.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'ByteByteGo',
          resourceType: ResourceType.VIDEO,
          learningOrder: 2,
          url: 'https://www.youtube.com/watch?v=F5D5p413g5E&list=PLy5w9wFkC93L3h43vPj5A4k5dE5vA_qA6',
          level: CourseLevel.BEGINNER,
          durationMin: 180,
          isPaid: false,
          qualityScore: 96,
        },
        {
          title: 'Grokking Modern System Design Interview',
          description: 'Outstanding structured text course covering real-world systems like YouTube, Twitter, and Netflix.',
          provider: ResourceProvider.OTHER,
          providerLabel: 'Educative.io',
          resourceType: ResourceType.COURSE,
          learningOrder: 3,
          url: 'https://www.educative.io/courses/grokking-modern-system-design-interview',
          level: CourseLevel.INTERMEDIATE,
          durationMin: 720,
          isPaid: true,
          qualityScore: 98,
        }
      ]
    },
    {
      name: 'CI/CD',
      hiringDemand: HiringDemand.IMPORTANT,
      estimatedWeeks: 2,
      projectSuggestion: 'Create a GitHub Actions workflow to build, test, and containerize an application',
      projectDifficulty: SkillDifficulty.INTERMEDIATE,
      projectHours: 4,
      projectOutcome: 'Show automated delivery skills: "Created complete GitHub Actions CI/CD pipeline triggering unit tests, building Docker images, and pushing to Docker Registry"',
      resources: [
        {
          title: 'GitHub Actions Documentation',
          description: 'Official reference for writing YAML workflows, triggers, actions, and custom runners.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'GitHub Actions Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://docs.github.com/en/actions',
          level: CourseLevel.BEGINNER,
          durationMin: 90,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'GitHub Skills - Continuous Integration',
          description: 'Official interactive lab by GitHub to configure an integration workflow.',
          provider: ResourceProvider.GITHUB,
          providerLabel: 'GitHub Skills',
          resourceType: ResourceType.INTERACTIVE,
          learningOrder: 2,
          url: 'https://github.com/skills/continuous-integration',
          level: CourseLevel.BEGINNER,
          durationMin: 60,
          isPaid: false,
          qualityScore: 98,
        },
        {
          title: 'CI/CD Pipeline Tutorial for Beginners',
          description: 'Clear structural guide explaining automation concepts, build servers, artifacts, and staging environments.',
          provider: ResourceProvider.YOUTUBE,
          providerLabel: 'TechWorld with Nana',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=scEDHsr3APg',
          level: CourseLevel.BEGINNER,
          durationMin: 150,
          isPaid: false,
          qualityScore: 95,
        }
      ]
    },
    {
      name: 'Linux',
      hiringDemand: HiringDemand.IMPORTANT,
      estimatedWeeks: 1,
      projectSuggestion: 'Configure a server with shell scripts, permissions, and service daemon',
      projectDifficulty: SkillDifficulty.BEGINNER,
      projectHours: 3,
      projectOutcome: 'Show basic server configuration on CV: "Authored Bash automation scripts and configured user permissions/systemd services on Linux servers"',
      resources: [
        {
          title: 'Linux Command Line Basics',
          description: 'Cheat sheet and structured guide for files, navigation, and permissions commands.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Linux Command Docs',
          resourceType: ResourceType.DOCS,
          learningOrder: 1,
          url: 'https://www.linux.org/pages/download/',
          level: CourseLevel.BEGINNER,
          durationMin: 45,
          isPaid: false,
          qualityScore: 100,
        },
        {
          title: 'Bash Guide for Beginners',
          description: 'Official guide covering variables, conditions, loops, and basic automation scripting.',
          provider: ResourceProvider.OFFICIAL_DOCS,
          providerLabel: 'Linux Documentation Project',
          resourceType: ResourceType.DOCS,
          learningOrder: 2,
          url: 'https://tldp.org/LDP/Bash-Beginners-Guide/html/',
          level: CourseLevel.BEGINNER,
          durationMin: 180,
          isPaid: false,
          qualityScore: 95,
        },
        {
          title: 'Linux Command Line Full Course',
          description: 'Comprehensive video overview of Unix directory structures, processes, SSH, package managers, and text editors (vim).',
          provider: ResourceProvider.FREECODECAMP,
          providerLabel: 'freeCodeCamp',
          resourceType: ResourceType.VIDEO,
          learningOrder: 3,
          url: 'https://www.youtube.com/watch?v=wbpMiKiSliA',
          level: CourseLevel.BEGINNER,
          durationMin: 340,
          isPaid: false,
          qualityScore: 94,
        }
      ]
    }
  ];

  for (const skillItem of skillData) {
    const existingSkill = await prisma.skill.findUnique({
      where: { name: skillItem.name }
    });

    if (!existingSkill) {
      console.log(`Skill '${skillItem.name}' not found, skipping updating metadata.`);
      continue;
    }

    // 1. Update skill metadata with hiringDemand & project details
    await prisma.skill.update({
      where: { id: existingSkill.id },
      data: {
        hiringDemand: skillItem.hiringDemand,
        estimatedWeeks: skillItem.estimatedWeeks,
        projectSuggestion: skillItem.projectSuggestion,
        projectDifficulty: skillItem.projectDifficulty,
        projectHours: skillItem.projectHours,
        projectOutcome: skillItem.projectOutcome,
      }
    });

    console.log(`- Updated metadata & project details for skill: ${skillItem.name}`);

    // 2. Clear old resources of this skill to prevent duplication/legacy links
    await prisma.learningResource.deleteMany({
      where: { skillId: existingSkill.id }
    });

    // 3. Create fresh resources
    for (const res of skillItem.resources) {
      const slug = `${skillItem.name.toLowerCase()}-${res.title.toLowerCase()}`
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '');

      await prisma.learningResource.create({
        data: {
          slug,
          title: res.title,
          description: res.description,
          provider: res.provider,
          providerLabel: res.providerLabel,
          resourceType: res.resourceType,
          learningOrder: res.learningOrder,
          url: res.url,
          skillId: existingSkill.id,
          level: res.level,
          durationMin: res.durationMin,
          isPaid: res.isPaid,
          qualityScore: res.qualityScore,
          status: ResourceStatus.ACTIVE,
          lastVerifiedAt: new Date(),
          httpStatus: 200,
        }
      });
    }

    console.log(`  - Seeded ${skillItem.resources.length} learning resources for skill: ${skillItem.name}`);
  }

  console.log('Learning resources seeding finished.');
}
